DROP TABLE IF EXISTS mpa, genres, films, film_genres, users, film_likes, user_friends;

CREATE TABLE IF NOT EXISTS mpa
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id BIGINT REFERENCES films (id),
    genre_id INTEGER REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id BIGINT REFERENCES films (id),
    user_id BIGINT REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS user_friends
(
    user_id BIGINT REFERENCES users (id),
    friend_id BIGINT REFERENCES users (id)
);